name: "`/www` checks"

on:
  # push:
  #   paths:
  #     - "www/**"
  #     - ".github/workflows/check-www.yml"
  pull_request:
    paths:
      - "www/**"
      - ".github/workflows/check-www.yml"

jobs:
  check:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: www/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: www

      - name: Typecheck
        run: npm run typecheck
        working-directory: www

      - name: Build
        run: npm run build
        working-directory: www
